mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: JP - zhuhai.uk
  type: hysteria2
  server: jpaw7.awo-link.com
  port: 14101
  password: 53b59cb5-c741-3399-9065-93dc34685f5b
  sni: jpaw7.awo-link.com
  obfs: salamander
  obfs-password: XBvVbvzQCq6Ovbnh
- name: US - zhuhai.uk
  type: http
  server: 138.199.35.213
  port: 9002
  username: 'null'
  password: 'null'
  tls: true
  skip-cert-verify: true
- name: US - zhuhai.uk 02
  type: http
  server: 156.146.59.46
  port: 9002
  tls: true
  sni: 156.146.59.46
  skip-cert-verify: true
- name: NL - zhuhai.uk
  type: http
  server: 84.17.47.148
  port: 9002
  tls: true
  skip-cert-verify: true
- name: NL - zhuhai.uk 02
  type: http
  server: 82.196.9.7
  port: 443
  username: testuser1
  password: e4b72b531a2d10900519
  tls: true
  sni: 52c40907.acsnet.co
  skip-cert-verify: true
- name: MY - zhuhai.uk
  type: vless
  server: 155.117.199.12
  port: 29711
  uuid: 53b59cb5-c741-3399-9065-93dc34685f5b
  flow: xtls-rprx-vision
  tls: true
  servername: cdnjs.cloudflare.com
  client-fingerprint: chrome
  reality-opts:
    public-key: JrWOojSFwFA93YjsiQkDydTItQzNAsXsHU24HuWGWjA
    short-id: bc8e3658db7d1323
- name: US - zhuhai.uk 03
  type: http
  server: 138.199.35.210
  port: 9002
  tls: true
  sni: 138.199.35.210
  skip-cert-verify: true
- name: KR - zhuhai.uk
  type: vless
  server: 155.117.199.12
  port: 39211
  uuid: 53b59cb5-c741-3399-9065-93dc34685f5b
  flow: xtls-rprx-vision
  tls: true
  servername: cdnjs.cloudflare.com
  skip-cert-verify: true
  client-fingerprint: chrome
  reality-opts:
    public-key: JrWOojSFwFA93YjsiQkDydTItQzNAsXsHU24HuWGWjA
    short-id: bc8e3658db7d1323
- name: KR - zhuhai.uk 02
  type: vless
  server: 188.253.123.164
  port: 39501
  uuid: 53b59cb5-c741-3399-9065-93dc34685f5b
  flow: xtls-rprx-vision
  tls: true
  servername: cdnjs.cloudflare.com
  client-fingerprint: chrome
  reality-opts:
    public-key: JrWOojSFwFA93YjsiQkDydTItQzNAsXsHU24HuWGWjA
    short-id: bc8e3658db7d1323
- name: JP - zhuhai.uk 02
  type: http
  server: fan.571589.xyz
  port: 443
  tls: true
  sni: fan.571589.xyz
  skip-cert-verify: true
- name: GB - zhuhai.uk
  type: http
  server: c0a5bcb4-thtxc0-ths4hq-azvy.cldvpuk.cdnbytescm.com
  port: 443
  username: a95e9198-0671-11f0-9426-f23c932f2c32
  password: a95e9198-0671-11f0-9426-f23c932f2c32
  tls: true
  sni: c0a5bcb4-thtxc0-ths4hq-azvy.cldvpuk.cdnbytescm.com
  skip-cert-verify: true
- name: US - zhuhai.uk 04
  type: http
  server: 138.199.35.204
  port: 9002
  tls: true
  skip-cert-verify: true
- name: RO - zhuhai.uk
  type: http
  server: 84.239.14.152
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: NL - zhuhai.uk 03
  type: vmess
  server: 185.246.152.159
  port: 443
  uuid: 5f72f180-b21b-4b7a-8484-240759012604
  alterId: 0
  cipher: auto
  tls: true
  servername: apjhdggyx.com
  network: ws
  ws-opts:
    path: "/5f72f180-b21b-4b7a-8484-240759096785"
    headers:
      Host: apjhdggyx.com
- name: DE - zhuhai.uk
  type: vless
  server: 191.44.108.152
  port: 443
  uuid: 20717e25-8cea-4634-b9ab-9c9bc9ca0620
  flow: xtls-rprx-vision
  tls: true
  servername: www.nvidia.com
  client-fingerprint: firefox
  reality-opts:
    public-key: vs39cITZN6jMHKslRMmvkwXupHXUbyKNX1MQsWRWKlg
    short-id: 3f40efc7
- name: SG - zhuhai.uk
  type: vless
  server: 155.117.199.12
  port: 31877
  uuid: 53b59cb5-c741-3399-9065-93dc34685f5b
  flow: xtls-rprx-vision
  tls: true
  servername: cdnjs.cloudflare.com
  client-fingerprint: chrome
  reality-opts:
    public-key: JrWOojSFwFA93YjsiQkDydTItQzNAsXsHU24HuWGWjA
    short-id: bc8e3658db7d1323
- name: US - zhuhai.uk 05
  type: http
  server: 209.148.53.153
  port: 8090
  tls: true
  skip-cert-verify: true
- name: US - zhuhai.uk 06
  type: vless
  server: 104.17.153.219
  port: 443
  uuid: cf63446e-f6b7-4d34-b7ed-d8648eeed0f7
  tls: true
  servername: vps.181110.xyz
  client-fingerprint: chrome
  network: ws
  ws-opts:
    path: "/cf63446e-vl"
    headers:
      Host: vps.181110.xyz
- name: RO - zhuhai.uk 02
  type: http
  server: 84.239.14.160
  port: 9002
  tls: true
  sni: 84.239.14.160
  skip-cert-verify: true
- name: DE - zhuhai.uk 02
  type: vless
  server: de3.neobo-tooth.ru
  port: 2053
  uuid: b6c29ae7-4748-4049-b642-b695c0d2c776
  flow: xtls-rprx-vision
  tls: true
  servername: vk.ru
  client-fingerprint: safari
  reality-opts:
    public-key: E6u2RbffXIPvia5v5iIZVj6U_VpSBWmGTsHHNtH-5Rg
    short-id: 417063feab794131
- name: US - zhuhai.uk 07
  type: http
  server: 38.28.193.1
  port: 443
  tls: true
  skip-cert-verify: true
- name: RO - zhuhai.uk 03
  type: http
  server: 84.239.49.41
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: US - zhuhai.uk 08
  type: vless
  server: 104.17.146.67
  port: 443
  uuid: cf63446e-f6b7-4d34-b7ed-d8648eeed0f7
  tls: true
  servername: vps.181110.xyz
  client-fingerprint: chrome
  network: ws
  ws-opts:
    path: "/cf63446e-vl"
    headers:
      Host: vps.181110.xyz
- name: RO - zhuhai.uk 04
  type: http
  server: 84.239.49.173
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: US - zhuhai.uk 09
  type: http
  server: 138.199.35.206
  port: 9002
  username: 'null'
  password: 'null'
  tls: true
  skip-cert-verify: true
- name: RO - zhuhai.uk 05
  type: http
  server: 84.239.49.227
  port: 9002
  tls: true
  sni: 84.239.49.227
  skip-cert-verify: true
- name: RO - zhuhai.uk 06
  type: http
  server: 84.239.49.47
  port: 9002
  tls: true
  sni: 84.239.49.47
  skip-cert-verify: true
- name: RO - zhuhai.uk 07
  type: http
  server: 84.239.49.244
  port: 9002
  tls: true
  skip-cert-verify: true
- name: RO - zhuhai.uk 08
  type: http
  server: 84.239.14.155
  port: 9002
  tls: true
  skip-cert-verify: true
- name: GB - zhuhai.uk 04
  type: http
  server: 73721193-tcxds0-tvgkxc-hrtf.uk.oshuawei.com
  port: 443
  username: 0da8651e-e1f6-11ec-bd7c-f23c913c8d2b
  password: 0da8651e-e1f6-11ec-bd7c-f23c913c8d2b
  tls: true
- name: GB - zhuhai.uk 06
  type: http
  server: c0a5bcb4-thtxc0-ths4hq-azvy.cldvpuk.cdnbytescm.com
  port: 443
  username: a95e9198-0671-11f0-9426-f23c932f2c32
  password: a95e9198-0671-11f0-9426-f23c932f2c32
  tls: true
- name: TW - zhuhai.uk 03
  type: socks5
  server: 106.107.236.110
  port: 1080
  udp: true
  username: '111'
  password: '111'
proxy-groups:
- name: 选择出口
  type: select
  proxies:
  - DIRECT
  - JP - zhuhai.uk
  - US - zhuhai.uk
  - US - zhuhai.uk 02
  - NL - zhuhai.uk
  - NL - zhuhai.uk 02
  - MY - zhuhai.uk
  - US - zhuhai.uk 03
  - KR - zhuhai.uk
  - KR - zhuhai.uk 02
  - JP - zhuhai.uk 02
  - GB - zhuhai.uk
  - US - zhuhai.uk 04
  - RO - zhuhai.uk
  - NL - zhuhai.uk 03
  - DE - zhuhai.uk
  - SG - zhuhai.uk
  - US - zhuhai.uk 05
  - US - zhuhai.uk 06
  - RO - zhuhai.uk 02
  - DE - zhuhai.uk 02
  - US - zhuhai.uk 07
  - RO - zhuhai.uk 03
  - US - zhuhai.uk 08
  - RO - zhuhai.uk 04
  - US - zhuhai.uk 09
  - RO - zhuhai.uk 05
  - RO - zhuhai.uk 06
  - RO - zhuhai.uk 07
  - RO - zhuhai.uk 08
  - GB - zhuhai.uk 04
  - GB - zhuhai.uk 06
  - TW - zhuhai.uk 03
rules:
- GEOSITE,CN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,选择出口
