mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: JP - zhuhai.uk
  type: trojan
  server: oplosgru-c.catcat321.com
  port: 20004
  password: ba07a8af-5544-48ac-ab62-3b6c00a44fa6
  tls: true
  sni: hk.catxstar.com
- name: RO - zhuhai.uk
  type: http
  server: 84.239.49.157
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: US - zhuhai.uk
  type: http
  server: 138.199.35.205
  port: 9002
  username: 'null'
  password: 'null'
  tls: true
  skip-cert-verify: true
- name: US - zhuhai.uk 02
  type: vless
  server: cos-cdn-m.alicdn.win
  port: 443
  uuid: c95edc3e-cb00-4504-ae38-9d36d96a08ca
  tls: true
  servername: mms-statlc-hxzy-f.hzedu.men
  client-fingerprint: edge
  network: ws
  ws-opts:
    path: "/newlogin/login.do"
    headers:
      Host: mms-static-gzip-f.hzedu.men
- name: RO - zhuhai.uk 02
  type: http
  server: 84.239.14.149
  port: 9002
  tls: true
  skip-cert-verify: true
- name: GB - zhuhai.uk
  type: trojan
  server: hkdcrtc-e.catcat321.com
  port: 20041
  password: ba07a8af-5544-48ac-ab62-3b6c00a44fa6
  tls: true
  sni: de.catxstar.com
  skip-cert-verify: true
- name: RO - zhuhai.uk 03
  type: http
  server: 84.239.49.207
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: RO - zhuhai.uk 04
  type: http
  server: 84.239.49.199
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: RO - zhuhai.uk 05
  type: http
  server: 84.239.49.198
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: JP - zhuhai.uk 02
  type: ss
  server: tc1.stmoym.com
  port: 43556
  cipher: chacha20-ietf-poly1305
  password: 406046ee1a41e85dc21ca0124c7f3baf
- name: GB - zhuhai.uk 02
  type: vless
  server: 88.218.44.4
  port: 8443
  uuid: e6d41d6f-d58a-7650-bba4-d7f0dde3ba4d
  tls: true
  servername: download.nvidia.com
  client-fingerprint: firefox
  network: grpc
  grpc-opts:
    grpc-service-name: TunService
  reality-opts:
    public-key: EG3y7UktGRlzSZZ2oXT_YaO2gVP4ca3Xe6AQ0u9A5DQ
- name: FR - zhuhai.uk
  type: http
  server: 8a7d3033-ta1og0-ta5i1s-1j61y.fr.oshuawei.com
  port: 443
  username: f13f964e-f06c-11ec-a858-f23c91cfbbc9
  password: f13f964e-f06c-11ec-a858-f23c91cfbbc9
  tls: true
  sni: 8a7d3033-ta1og0-ta5i1s-1j61y.fr.oshuawei.com
  skip-cert-verify: true
- name: RO - zhuhai.uk 06
  type: http
  server: 84.239.49.212
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: HK - zhuhai.uk
  type: socks5
  server: 124.156.185.140
  port: 1080
- name: RO - zhuhai.uk 07
  type: http
  server: 84.239.49.49
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: RO - zhuhai.uk 08
  type: http
  server: 84.239.49.176
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: HK - zhuhai.uk 02
  type: socks5
  server: 47.75.116.41
  port: 10800
- name: NL - zhuhai.uk
  type: vless
  server: 84.235.165.206
  port: 62145
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
- name: HK - zhuhai.uk 03
  type: vless
  server: 162.159.137.204
  port: 443
  uuid: 68eee13f-1a7a-4761-b71e-83b997eeccf9
  tls: true
  servername: dnpjl.emrb.1uu.hh.hhyf.kdns.fr
  client-fingerprint: chrome
  network: ws
  ws-opts:
    path: "/glasspanel/92298abb_0_5744c010dde7/"
    headers:
      Host: dnpjl.emrb.1uu.hh.hhyf.kdns.fr
- name: HK - zhuhai.uk 04
  type: vless
  server: cos-cdn-b.alicdn.win
  port: 443
  uuid: c95edc3e-cb00-4504-ae38-9d36d96a08ca
  tls: true
  servername: mms-statlc-y2fnp-e.codeu.men
  client-fingerprint: edge
  network: ws
  ws-opts:
    path: "/newlogin/login.do"
    headers:
      Host: mms-static-fetch-e.codeu.men
- name: GB - zhuhai.uk 03
  type: ss
  server: 144.24.229.124
  port: 61312
  cipher: chacha20-ietf-poly1305
  password: MGU4ZjVkMGNhY2Y3YzM0NmIxMDgyNDQ5OGVjZjY2Y2Y=
- name: US - zhuhai.uk 03
  type: http
  server: 138.199.35.212
  port: 9002
  tls: true
  skip-cert-verify: true
- name: HK - zhuhai.uk 05
  type: trojan
  server: 106.75.132.91
  port: 30428
  password: 55354c2b8ee339571bd657a9bb9858cc
  tls: true
  skip-cert-verify: true
- name: RO - zhuhai.uk 09
  type: http
  server: 84.239.49.208
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: US - zhuhai.uk 04
  type: vless
  server: 152.70.119.78
  port: 443
  uuid: 68eee13f-1a7a-4761-b71e-83b997eeccf9
  tls: true
  servername: dnpjl.emrb.1uu.hh.hhyf.kdns.fr
  client-fingerprint: chrome
  network: ws
  ws-opts:
    path: "/glasspanel/92298abb_0_5744c010dde7/"
    headers:
      Host: dnpjl.emrb.1uu.hh.hhyf.kdns.fr
- name: US - zhuhai.uk 05
  type: vless
  server: 43.162.83.82
  port: 666
  uuid: 8d5e7f2a-3c1b-4d9e-a6f8-2b5c0e7d4a19
  tls: true
  servername: 43.162.83.82
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: "/proxy"
    headers:
      Host: 43.162.83.82
- name: RO - zhuhai.uk 10
  type: http
  server: 84.239.49.176
  port: 9002
  tls: true
  skip-cert-verify: true
- name: US - zhuhai.uk 06
  type: http
  server: 138.199.35.195
  port: 9002
  username: 'null'
  password: None
  tls: true
  skip-cert-verify: true
- name: RO - zhuhai.uk 11
  type: http
  server: 193.176.84.37
  port: 9002
  tls: true
  skip-cert-verify: true
- name: SG - zhuhai.uk
  type: socks5
  server: 45.43.63.37
  port: 10808
- name: AU - zhuhai.uk 03
  type: socks5
  server: 213.199.47.140
  port: 1080
  udp: true
- name: NL - zhuhai.uk 02
  type: socks5
  server: 85.17.179.81
  port: 1080
  udp: true
  username: M_YOU_D
  password: Private
- name: FR - zhuhai.uk 02
  type: socks5
  server: 213.199.47.140
  port: 1080
  udp: true
- name: FR - zhuhai.uk 03
  type: socks5
  server: 213.199.47.140
  port: 1080
  udp: true
- name: NL - zhuhai.uk 04
  type: socks5
  server: 85.17.179.81
  port: 1080
  udp: true
  username: M_YOU_D
  password: Private
- name: DE - zhuhai.uk 07
  type: trojan
  server: hkdcrtc-e.catcat321.com
  port: 20041
  password: ba07a8af-5544-48ac-ab62-3b6c00a44fa6
  udp: true
  sni: de.catxstar.com
  skip-cert-verify: true
- name: GB - zhuhai.uk 05
  type: http
  server: 5c78e09e-thxmo0-tjdj5q-azvy.cldvpuk.cdnbytescm.com
  port: 443
  username: a95e9198-0671-11f0-9426-f23c932f2c32
  password: a95e9198-0671-11f0-9426-f23c932f2c32
  tls: true
- name: KR - zhuhai.uk 03
  type: socks5
  server: 43.164.136.189
  port: 1080
  udp: true
- name: JP - zhuhai.uk 48
  type: trojan
  server: oplosgru-c.catcat321.com
  port: 20004
  password: ba07a8af-5544-48ac-ab62-3b6c00a44fa6
  udp: true
  sni: hk.catxstar.com
  skip-cert-verify: true
- name: KR - zhuhai.uk 02
  type: socks5
  server: 43.164.136.189
  port: 1080
  udp: true
proxy-groups:
- name: 选择出口
  type: select
  proxies:
  - DIRECT
  - JP - zhuhai.uk
  - RO - zhuhai.uk
  - US - zhuhai.uk
  - US - zhuhai.uk 02
  - RO - zhuhai.uk 02
  - GB - zhuhai.uk
  - RO - zhuhai.uk 03
  - RO - zhuhai.uk 04
  - RO - zhuhai.uk 05
  - JP - zhuhai.uk 02
  - GB - zhuhai.uk 02
  - FR - zhuhai.uk
  - RO - zhuhai.uk 06
  - HK - zhuhai.uk
  - RO - zhuhai.uk 07
  - RO - zhuhai.uk 08
  - HK - zhuhai.uk 02
  - NL - zhuhai.uk
  - HK - zhuhai.uk 03
  - HK - zhuhai.uk 04
  - GB - zhuhai.uk 03
  - US - zhuhai.uk 03
  - HK - zhuhai.uk 05
  - RO - zhuhai.uk 09
  - US - zhuhai.uk 04
  - US - zhuhai.uk 05
  - RO - zhuhai.uk 10
  - US - zhuhai.uk 06
  - RO - zhuhai.uk 11
  - SG - zhuhai.uk
  - AU - zhuhai.uk 03
  - NL - zhuhai.uk 02
  - FR - zhuhai.uk 02
  - FR - zhuhai.uk 03
  - NL - zhuhai.uk 04
  - DE - zhuhai.uk 07
  - GB - zhuhai.uk 05
  - KR - zhuhai.uk 03
  - JP - zhuhai.uk 48
  - KR - zhuhai.uk 02
rules:
- GEOSITE,CN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,选择出口
