mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: RO - zhuhai.uk
  type: http
  server: 84.239.49.50
  port: 9002
  tls: true
  skip-cert-verify: true
- name: DE - zhuhai.uk
  type: vless
  server: 151.101.193.54
  port: 80
  uuid: c9380ef8-23f8-422e-81fe-ebbb032202cf
  network: ws
  ws-opts:
    path: "/"
    headers:
      Host: BankMelat.glObal.ssl.faStly.nEt.
- name: RO - zhuhai.uk 02
  type: http
  server: 84.239.49.161
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: RO - zhuhai.uk 03
  type: http
  server: 84.239.49.53
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: US - zhuhai.uk
  type: socks5
  server: 23.175.248.21
  port: 1080
- name: RO - zhuhai.uk 04
  type: http
  server: 84.239.14.153
  port: 9002
  tls: true
  skip-cert-verify: true
- name: RO - zhuhai.uk 05
  type: http
  server: 84.239.49.245
  port: 9002
  tls: true
  skip-cert-verify: true
- name: DE - zhuhai.uk 02
  type: vless
  server: 194.93.0.28
  port: 443
  uuid: 218fd696-e3a2-4c33-b397-a5f13a82969e
  tls: true
  servername: media2.tcpdoor.net
  client-fingerprint: chrome
  network: grpc
  grpc-opts:
    grpc-service-name: grpc
  reality-opts:
    public-key: vxhkDXfYpz1OLqZ-_9QVoQr3_UJLtJFheb5bD5YH7z8
    short-id: 3303c7a5
- name: RO - zhuhai.uk 06
  type: http
  server: 84.239.49.165
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: FI - zhuhai.uk
  type: vless
  server: 140.233.160.24
  port: 443
  uuid: da7685a7-15ef-41e4-a0d9-009bb4be7220
  flow: xtls-rprx-vision
  tls: true
  servername: ya.ru
  client-fingerprint: edge
  reality-opts:
    public-key: V6FabatADtcX7aO9KMjGCadJC4LuQ_5nRViab-z-nFQ
    short-id: abcd
- name: RO - zhuhai.uk 07
  type: http
  server: 84.239.49.225
  port: 9002
  tls: true
  skip-cert-verify: true
- name: RO - zhuhai.uk 08
  type: http
  server: 84.239.14.146
  port: 9002
  tls: true
  skip-cert-verify: true
- name: RO - zhuhai.uk 09
  type: http
  server: 193.176.84.23
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: SG - zhuhai.uk
  type: hysteria2
  server: taga8.api3-max.ru
  port: 443
  password: 67a1454f-5a95-4e30-9723-1ffcbe7e97f9
  sni: taga8.api3-max.ru
- name: RO - zhuhai.uk 10
  type: http
  server: 84.239.49.41
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: RO - zhuhai.uk 11
  type: http
  server: 84.239.49.239
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: RO - zhuhai.uk 12
  type: http
  server: 84.239.49.240
  port: 9002
  tls: true
  skip-cert-verify: true
- name: RU - zhuhai.uk
  type: vless
  server: cdn-spb.buildsnow.top
  port: 443
  uuid: f9922bed-4524-4a6a-8709-9c2e26dedee9
  tls: true
  servername: cdn-spb.buildsnow.top
  client-fingerprint: edge
  network: grpc
  grpc-opts:
    grpc-service-name: cdn-spb.buildsnow.top
  reality-opts:
    public-key: SthWDW71MJzhV10XWlbGwdc0BJ6W1ILfny_xn2D0e1A
    short-id: 0ac1b591aafcfa51
- name: RO - zhuhai.uk 13
  type: http
  server: 84.239.49.209
  port: 9002
  tls: true
  skip-cert-verify: true
- name: US - zhuhai.uk 02
  type: http
  server: 156.146.59.4
  port: 9002
  tls: true
  skip-cert-verify: true
- name: RO - zhuhai.uk 14
  type: http
  server: 84.239.49.253
  port: 9002
  tls: true
  skip-cert-verify: true
- name: RO - zhuhai.uk 15
  type: http
  server: 84.239.49.48
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: KR - zhuhai.uk
  type: socks5
  server: 158.180.91.51
  port: 5555
  username: admin
  password: admin
- name: FR - zhuhai.uk
  type: hysteria2
  server: vpn-fr-002.fastervpn.world
  port: 443
  password: H7mP2xY9kJ4nQ8wR5tF6vB3z
  sni: vpn-fr-002.fastervpn.world
  skip-cert-verify: true
- name: RO - zhuhai.uk 16
  type: http
  server: 84.239.14.156
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: RO - zhuhai.uk 17
  type: http
  server: 84.239.14.159
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: US - zhuhai.uk 03
  type: http
  server: 156.146.59.47
  port: 9002
  tls: true
  skip-cert-verify: true
- name: MY - zhuhai.uk
  type: socks5
  server: 51.222.104.72
  port: 1080
- name: RO - zhuhai.uk 18
  type: http
  server: 84.239.14.146
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: RO - zhuhai.uk 19
  type: http
  server: 84.239.49.228
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: RO - zhuhai.uk 20
  type: http
  server: 84.239.49.248
  port: 9002
  tls: true
  skip-cert-verify: true
- name: CA - zhuhai.uk 01
  type: vless
  server: cf.130209.xyz
  port: 443
  uuid: 65c56e1f-5c41-40bc-b0b5-9346772476ca
  udp: true
  network: ws
  tls: true
  servername: canda.usic.ccwu.cc
  client-fingerprint: edge
  ws-opts:
    path: "/api/v2/check_update"
    headers:
      Host: canda.usic.ccwu.cc
- name: US - zhuhai.uk 01
  type: vless
  server: us2-r.link-t7.com
  port: 10239
  uuid: 6BA21C4F-87EA-43D9-B0C9-BCD40900DAF8
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: movie
- name: US - zhuhai.uk 06
  type: vless
  server: phoenix.maimaiyun.shop
  port: 20001
  uuid: 65c56e1f-5c41-40bc-b0b5-9346772476ca
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: identity.oraclecloud.com
  client-fingerprint: edge
  reality-opts:
    public-key: x-SY8-gdy6LPtfJXNH9s9S4I7o2mTI2T8i3R5KAa5TY
    short-id: 07f9d8acd616bd
- name: JP - zhuhai.uk 04
  type: vless
  server: 14.137.238.159
  port: 10000
  uuid: 431fe973-a43a-4fac-bf83-2a772e0d0625
  udp: true
  network: tcp
- name: TW - zhuhai.uk 06
  type: vless
  server: 60.249.101.14
  port: 10000
  uuid: 431fe973-a43a-4fac-bf83-2a772e0d0625
  udp: true
  network: tcp
- name: TW - zhuhai.uk 03
  type: vless
  server: 60.249.101.16
  port: 10000
  uuid: 431fe973-a43a-4fac-bf83-2a772e0d0625
  udp: true
  network: tcp
- name: JP - zhuhai.uk 09
  type: vless
  server: jp5-r.link-t7.com
  port: 10035
  uuid: 65ED2A4D-E1DB-4310-AB85-65C711BA873A
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: HK - zhuhai.uk 03
  type: vless
  server: 207.174.133.222
  port: 10000
  uuid: 431fe973-a43a-4fac-bf83-2a772e0d0625
  udp: true
  network: tcp
- name: JP - zhuhai.uk 07
  type: vless
  server: jp3-r.link-t7.com
  port: 10033
  uuid: 65ED2A4D-E1DB-4310-AB85-65C711BA873A
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: JP - zhuhai.uk 06
  type: vless
  server: jp2-r.link-t7.com
  port: 10032
  uuid: 65ED2A4D-E1DB-4310-AB85-65C711BA873A
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: JP - zhuhai.uk 05
  type: vless
  server: jp1-r.link-t7.com
  port: 10031
  uuid: 65ED2A4D-E1DB-4310-AB85-65C711BA873A
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: JP - zhuhai.uk 03
  type: vless
  server: jp3-r.link-t7.com
  port: 10033
  uuid: 6BA21C4F-87EA-43D9-B0C9-BCD40900DAF8
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: JP - zhuhai.uk 10
  type: vless
  server: jp6-r.link-t7.com
  port: 10036
  uuid: 65ED2A4D-E1DB-4310-AB85-65C711BA873A
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: JP - zhuhai.uk 01
  type: vless
  server: jp5-r.link-t7.com
  port: 10035
  uuid: 6BA21C4F-87EA-43D9-B0C9-BCD40900DAF8
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: KR - zhuhai.uk 08
  type: vless
  server: kr3-r.link-t7.com
  port: 10048
  uuid: 65ED2A4D-E1DB-4310-AB85-65C711BA873A
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: KR - zhuhai.uk 04
  type: vless
  server: kr4-r.link-t7.com
  port: 10049
  uuid: 6BA21C4F-87EA-43D9-B0C9-BCD40900DAF8
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: KR - zhuhai.uk 10
  type: vless
  server: kr5-r.link-t7.com
  port: 10050
  uuid: 65ED2A4D-E1DB-4310-AB85-65C711BA873A
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: KR - zhuhai.uk 09
  type: vless
  server: kr4-r.link-t7.com
  port: 10049
  uuid: 65ED2A4D-E1DB-4310-AB85-65C711BA873A
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: KR - zhuhai.uk 07
  type: vless
  server: kr2-r.link-t7.com
  port: 10047
  uuid: 65ED2A4D-E1DB-4310-AB85-65C711BA873A
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: KR - zhuhai.uk 03
  type: vless
  server: kr3-r.link-t7.com
  port: 10048
  uuid: 6BA21C4F-87EA-43D9-B0C9-BCD40900DAF8
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: KR - zhuhai.uk 02
  type: vless
  server: kr2-r.link-t7.com
  port: 10047
  uuid: 6BA21C4F-87EA-43D9-B0C9-BCD40900DAF8
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: KR - zhuhai.uk 05
  type: vless
  server: kr5-r.link-t7.com
  port: 10050
  uuid: 6BA21C4F-87EA-43D9-B0C9-BCD40900DAF8
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: MO - zhuhai.uk 01
  type: vless
  server: 45.207.34.239
  port: 10086
  uuid: 11e5e68c-355a-415c-8024-3bf12637e220
  udp: true
  network: ws
  ws-opts:
    path: "/vless"
- name: SG - zhuhai.uk 04
  type: vless
  server: sg1-r.link-t7.com
  port: 10036
  uuid: 65ED2A4D-E1DB-4310-AB85-65C711BA873A
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: SG - zhuhai.uk 02
  type: vless
  server: sg4-r.link-t7.com
  port: 10039
  uuid: 6BA21C4F-87EA-43D9-B0C9-BCD40900DAF8
  udp: true
  network: grpc
  tls: true
  servername: d1.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: SG - zhuhai.uk 06
  type: vless
  server: sg3-r.link-t7.com
  port: 10038
  uuid: 65ED2A4D-E1DB-4310-AB85-65C711BA873A
  udp: true
  network: grpc
  tls: true
  servername: d1.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: SG - zhuhai.uk 05
  type: vless
  server: sg2-r.link-t7.com
  port: 10037
  uuid: 65ED2A4D-E1DB-4310-AB85-65C711BA873A
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: SG - zhuhai.uk 01
  type: vless
  server: sg1-r.link-t7.com
  port: 10036
  uuid: 6BA21C4F-87EA-43D9-B0C9-BCD40900DAF8
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: update
- name: US - zhuhai.uk 04
  type: vless
  server: us5-r.link-t7.com
  port: 10242
  uuid: 65ED2A4D-E1DB-4310-AB85-65C711BA873A
  udp: true
  network: grpc
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: chrome
  reality-opts:
    public-key: wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE
    short-id: 686c0ef0
  grpc-opts:
    grpc-service-name: movie
- name: US - zhuhai.uk 07
  type: vless
  server: zz.j-pan.ccwu.cc
  port: 30001
  uuid: 65c56e1f-5c41-40bc-b0b5-9346772476ca
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: edge
  reality-opts:
    public-key: 1jkizvy42aHc-um3C7LgmBYRn6HFJomyk0F2T_i2PwA
    short-id: 6d9478ae
- name: DE - zhuhai.uk 01
  type: vless
  server: hongkong.xmm.maimaiyun.shop
  port: 30001
  uuid: 65c56e1f-5c41-40bc-b0b5-9346772476ca
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: s0.awsstatic.com
  client-fingerprint: edge
  reality-opts:
    public-key: DXhNIS_BYchI7piB2tSMrntuYhPPkwXX9PZTnmw7YBo
    short-id: 1f098dbd3d
proxy-groups:
- name: 选择出口
  type: select
  proxies:
  - DIRECT
  - RO - zhuhai.uk
  - DE - zhuhai.uk
  - RO - zhuhai.uk 02
  - RO - zhuhai.uk 03
  - US - zhuhai.uk
  - RO - zhuhai.uk 04
  - RO - zhuhai.uk 05
  - DE - zhuhai.uk 02
  - RO - zhuhai.uk 06
  - FI - zhuhai.uk
  - RO - zhuhai.uk 07
  - RO - zhuhai.uk 08
  - RO - zhuhai.uk 09
  - SG - zhuhai.uk
  - RO - zhuhai.uk 10
  - RO - zhuhai.uk 11
  - RO - zhuhai.uk 12
  - RU - zhuhai.uk
  - RO - zhuhai.uk 13
  - US - zhuhai.uk 02
  - RO - zhuhai.uk 14
  - RO - zhuhai.uk 15
  - KR - zhuhai.uk
  - FR - zhuhai.uk
  - RO - zhuhai.uk 16
  - RO - zhuhai.uk 17
  - US - zhuhai.uk 03
  - MY - zhuhai.uk
  - RO - zhuhai.uk 18
  - RO - zhuhai.uk 19
  - RO - zhuhai.uk 20
  - CA - zhuhai.uk 01
  - US - zhuhai.uk 01
  - US - zhuhai.uk 06
  - JP - zhuhai.uk 04
  - TW - zhuhai.uk 06
  - TW - zhuhai.uk 03
  - JP - zhuhai.uk 09
  - HK - zhuhai.uk 03
  - JP - zhuhai.uk 07
  - JP - zhuhai.uk 06
  - JP - zhuhai.uk 05
  - JP - zhuhai.uk 03
  - JP - zhuhai.uk 10
  - JP - zhuhai.uk 01
  - KR - zhuhai.uk 08
  - KR - zhuhai.uk 04
  - KR - zhuhai.uk 10
  - KR - zhuhai.uk 09
  - KR - zhuhai.uk 07
  - KR - zhuhai.uk 03
  - KR - zhuhai.uk 02
  - KR - zhuhai.uk 05
  - MO - zhuhai.uk 01
  - SG - zhuhai.uk 04
  - SG - zhuhai.uk 02
  - SG - zhuhai.uk 06
  - SG - zhuhai.uk 05
  - SG - zhuhai.uk 01
  - US - zhuhai.uk 04
  - US - zhuhai.uk 07
  - DE - zhuhai.uk 01
rules:
- GEOSITE,CN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,选择出口
