proxies:
- name: DE - zhuhai.uk 02
  type: vless
  server: hht.hhlldjc.kdns.fr
  port: 443
  uuid: a4f61bab-947b-4451-b289-2e09962b9c9e
  udp: true
  network: ws
  tls: true
  servername: hht.hhlldjc.kdns.fr
  client-fingerprint: chrome
  ws-opts:
    path: "/fdip=turn://167.235.139.220:3479?global=0&ed=2560"
    headers:
      Host: hht.hhlldjc.kdns.fr
proxy-groups:
- name: EXTRA-LIVE
  type: select
  proxies:
  - DE - zhuhai.uk 02
